### ISSUE TITLE
How to add more streamers?

### ISSUE THREAD

**Issue by endingwithali** [whitep4nth3r/womenwhostream.tech#2]
I was looking through the code to see if I could add myself via PR or submission (hehehe) and couldn't find a way, so I was wondering if you will be opening up the process for being added to the list?

**Comment by whitep4nth3r** [comment]
I'll be adding a nomination form! The data is stored in Contentful – so I will get you added!

**Comment by endingwithali** [comment]
! awesome. thank you for the quick response :)

**Comment by whitep4nth3r** [comment]
You're on!
